<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateHorsesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('horses', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->charset = 'utf8';
            $table->collation = 'utf8_general_ci';
            
            $table->id();
            $table->integer('race_id');
            $table->integer("post_position");
            $table->integer('claiming_price_horse');
            $table->string('today_trainer', 60);
            $table->integer('today_trainer_sts');
            $table->integer('today_trainer_wins');
            $table->integer('today_trainer_places');
            $table->integer('today_trainer_shows');
            $table->string('today_jockey', 60);
            $table->integer('apprentice_wgt_allow');
            $table->integer('today_jockey_sts');
            $table->integer('today_jockey_wins');
            $table->integer('today_jockey_places');
            $table->integer('today_jockey_shows');
            $table->string('today_owner', 80);
            $table->string('owner_silks', 200);
            $table->string('main_track_only', 2);
            $table->string('reserved_0042', 2);
            $table->string('program_number', 2);
            $table->float('line_odds', 8, 2);
            $table->string('horse_name', 50);
            $table->integer('horse_birth_year');
            $table->integer('horse_foaling_month');
            $table->string('reserved_0048', 2);
            $table->string('horse_sex', 2);
            $table->string('horse_color', 10);
            $table->integer('horse_weight');
            $table->string('horse_sire', 50);
            $table->string('horse_sire_sire', 50);
            $table->string('horse_dam', 50);
            $table->string('horse_dam_sire', 50);
            $table->string('horse_breeder', 135);
            $table->string('horse_state_country', 10);
            $table->string('program_post_position', 4);
            $table->string('reserved_0059', 2);
            $table->string('reserved_0060', 2);
            $table->string('reserved_0061', 2);
            $table->integer('today_medication_new');
            $table->integer('today_medication_old');
            $table->integer('equipment_change');
            $table->integer('horse_lifetime_distance_record_starts');
            $table->integer('horse_lifetime_distance_record_wins');
            $table->integer('horse_lifetime_distance_record_places');
            $table->integer('horse_lifetime_distance_record_shows');
            $table->integer('horse_lifetime_distance_record_earnings');
            $table->integer('horse_lifetime_track_record_starts');
            $table->integer('horse_lifetime_track_record_wins');
            $table->integer('horse_lifetime_track_record_places');
            $table->integer('horse_lifetime_track_record_shows');
            $table->integer('horse_lifetime_track_record_earnings');
            $table->integer('horse_lifetime_turf_record_starts');
            $table->integer('horse_lifetime_turf_record_wins');
            $table->integer('horse_lifetime_turf_record_places');
            $table->integer('horse_lifetime_turf_record_shows');
            $table->integer('horse_lifetime_turf_record_earnings');
            $table->integer('horse_lifetime_wet_record_starts');
            $table->integer('horse_lifetime_wet_record_wins');
            $table->integer('horse_lifetime_wet_record_places');
            $table->integer('horse_lifetime_wet_record_shows');
            $table->integer('horse_lifetime_wet_record_earnings');
            $table->integer('horse_current_year_record_year');
            $table->integer('horse_current_year_record_starts');
            $table->integer('horse_current_year_record_wins');
            $table->integer('horse_current_year_record_places');
            $table->integer('horse_current_year_record_shows');
            $table->integer('horse_current_year_record_earnings');
            $table->integer('horse_previous_year_record_year');
            $table->integer('horse_previous_year_record_starts');
            $table->integer('horse_previous_year_record_wins');
            $table->integer('horse_previous_year_record_places');
            $table->integer('horse_previous_year_record_shows');
            $table->integer('horse_previous_year_record_earnings');
            $table->integer('horse_lifetime_record_starts');
            $table->integer('horse_lifetime_record_wins');
            $table->integer('horse_lifetime_record_places');
            $table->integer('horse_lifetime_record_shows');
            $table->integer('horse_lifetime_record_earnings');
            $table->string('bris_run_style_designation', 6);
            $table->integer('quirin_style_speed_points');
            $table->string('reserved_0212', 2);
            $table->string('reserved_0213', 2);
            $table->integer('two_f_bris_pace_par_for_level');
            $table->integer('four_f_bris_pace_par_for_level');
            $table->integer('six_f_bris_pace_par_for_level');
            $table->integer('bris_speed_par_for_class_level');
            $table->integer('bris_late_pace_par_for_level');
            $table->integer('tj_combo_starts');
            $table->integer('tj_combo_wins');
            $table->integer('tj_combo_places');
            $table->integer('tj_combo_shows');
            $table->integer('tj_combo_roi');
            $table->integer('days_since_last_race');
            $table->string('complete_race_condition_lines_1', 510);
            $table->string('complete_race_condition_lines_2', 510);
            $table->string('complete_race_condition_lines_3', 510);
            $table->string('complete_race_condition_lines_4', 510);
            $table->string('complete_race_condition_lines_5', 510);
            $table->string('complete_race_condition_lines_6', 510);
            $table->integer('lifetime_starts');
            $table->integer('lifetime_wins');
            $table->integer('lifetime_places');
            $table->integer('lifetime_shows');
            $table->integer('lifetime_earnings');
            $table->integer('best_bris_speed');
            $table->string('reserved_0237', 2);
            $table->integer('low_claiming_price');
            $table->string('statebred_flag_s', 2);
            $table->string('wager_types_this_race_1', 100);
            $table->string('wager_types_this_race_2', 100);
            $table->string('wager_types_this_race_3', 100);
            $table->string('wager_types_this_race_4', 100);
            $table->string('wager_types_this_race_5', 100);
            $table->string('wager_types_this_race_6', 100);
            $table->string('wager_types_this_race_7', 100);
            $table->string('wager_types_this_race_8', 100);
            $table->string('wager_types_this_race_9', 100);
            $table->string('reserved_0249', 2);
            $table->string('reserved_0250', 2);
            $table->float('bris_prime_power_rating', 8, 2);
            $table->string('reserved_0252', 2);
            $table->string('reserved_0253', 2);
            $table->string('reserved_0254', 2);
            $table->string('reserved_0255', 2);
            $table->string('reserved_1146', 2);
            $table->integer('trainer_sts_current_year');
            $table->integer('trainer_wins_current_year');
            $table->integer('trainer_places_current_year');
            $table->integer('trainer_shows_current_year');
            $table->float('trainer_roi_current_year', 8, 2);
            $table->integer('trainer_sts_previous_year');
            $table->integer('trainer_wins_previous_year');
            $table->integer('trainer_places_previous_year');
            $table->integer('trainer_shows_previous_year');
            $table->float('trainer_roi_previous_year', 8, 2);
            $table->integer('jockey_sts_current_year');
            $table->integer('jockey_wins_current_year');
            $table->integer('jockey_places_current_year');
            $table->integer('jockey_shows_current_year');
            $table->float('jockey_roi_current_year', 8, 2);
            $table->integer('jockey_sts_previous_year');
            $table->integer('jockey_wins_previous_year');
            $table->integer('jockey_places_previous_year');
            $table->integer('jockey_shows_previous_year');
            $table->float('jockey_roi_previous_year', 8, 2);
            $table->integer('bris_speed_par_for_class_level_last_races_0');
            $table->integer('bris_speed_par_for_class_level_last_races_1');
            $table->integer('bris_speed_par_for_class_level_last_races_2');
            $table->integer('bris_speed_par_for_class_level_last_races_3');
            $table->integer('bris_speed_par_for_class_level_last_races_4');
            $table->integer('bris_speed_par_for_class_level_last_races_5');
            $table->integer('bris_speed_par_for_class_level_last_races_6');
            $table->integer('bris_speed_par_for_class_level_last_races_7');
            $table->integer('bris_speed_par_for_class_level_last_races_8');
            $table->integer('bris_speed_par_for_class_level_last_races_9');
            $table->integer('sire_stud_fee');
            $table->integer('best_bris_speed_fast_track');
            $table->integer('best_bris_speed_turf');
            $table->integer('best_bris_speed_off_track');
            $table->integer('best_bris_speed_distance');
            $table->string('bar_shoe_0', 2);
            $table->string('bar_shoe_1', 2);
            $table->string('bar_shoe_2', 2);
            $table->string('bar_shoe_3', 2);
            $table->string('bar_shoe_4', 2);
            $table->string('bar_shoe_5', 2);
            $table->string('bar_shoe_6', 2);
            $table->string('bar_shoe_7', 2);
            $table->string('bar_shoe_8', 2);
            $table->string('bar_shoe_9', 2);
            $table->string('company_line_codes_0', 8);
            $table->string('company_line_codes_1', 8);
            $table->string('company_line_codes_2', 8);
            $table->string('company_line_codes_3', 8);
            $table->string('company_line_codes_4', 8);
            $table->string('company_line_codes_5', 8);
            $table->string('company_line_codes_6', 8);
            $table->string('company_line_codes_7', 8);
            $table->string('company_line_codes_8', 8);
            $table->string('company_line_codes_9', 8);
            $table->integer('low_claiming_price_race_0');
            $table->integer('low_claiming_price_race_1');
            $table->integer('low_claiming_price_race_2');
            $table->integer('low_claiming_price_race_3');
            $table->integer('low_claiming_price_race_4');
            $table->integer('low_claiming_price_race_5');
            $table->integer('low_claiming_price_race_6');
            $table->integer('low_claiming_price_race_7');
            $table->integer('low_claiming_price_race_8');
            $table->integer('low_claiming_price_race_9');
            $table->integer('high_claiming_price_race_0');
            $table->integer('high_claiming_price_race_1');
            $table->integer('high_claiming_price_race_2');
            $table->integer('high_claiming_price_race_3');
            $table->integer('high_claiming_price_race_4');
            $table->integer('high_claiming_price_race_5');
            $table->integer('high_claiming_price_race_6');
            $table->integer('high_claiming_price_race_7');
            $table->integer('high_claiming_price_race_8');
            $table->integer('high_claiming_price_race_9');
            $table->integer('auction_price');
            $table->string('sold_at_auction', 12);
            $table->string('reserved_1224', 2);
            $table->string('reserved_1225', 2);
            $table->string('reserved_1226', 2);
            $table->string('reserved_1227', 2);
            $table->string('reserved_1228', 2);
            $table->string('reserved_1229', 2);
            $table->string('reserved_1230', 2);
            $table->string('reserved_1231', 2);
            $table->string('reserved_1232', 2);
            $table->string('reserved_1233', 2);
            $table->string('reserved_1234', 2);
            $table->string('reserved_1235', 2);
            $table->string('reserved_1236', 2);
            $table->string('reserved_1237', 2);
            $table->string('reserved_1238', 2);
            $table->string('reserved_1239', 2);
            $table->string('reserved_1240', 2);
            $table->string('reserved_1241', 2);
            $table->string('reserved_1242', 2);
            $table->string('reserved_1243', 2);
            $table->string('reserved_1244', 2);
            $table->string('reserved_1245', 2);
            $table->string('reserved_1246', 2);
            $table->string('reserved_1247', 2);
            $table->string('reserved_1248', 2);
            $table->string('reserved_1249', 2);
            $table->string('reserved_1250', 2);
            $table->string('reserved_1251', 2);
            $table->string('reserved_1252', 2);
            $table->string('reserved_1253', 2);
            $table->string('code_for_prior_10_starts_0', 2);
            $table->string('code_for_prior_10_starts_1', 2);
            $table->string('code_for_prior_10_starts_2', 2);
            $table->string('code_for_prior_10_starts_3', 2);
            $table->string('code_for_prior_10_starts_4', 2);
            $table->string('code_for_prior_10_starts_5', 2);
            $table->string('code_for_prior_10_starts_6', 2);
            $table->string('code_for_prior_10_starts_7', 2);
            $table->string('code_for_prior_10_starts_8', 2);
            $table->string('code_for_prior_10_starts_9', 2);
            $table->string('bris_dirt_pedigree_rating', 8);
            $table->string('bris_mud_pedigree_rating', 8);
            $table->string('bris_turf_pedigree_rating', 8);
            $table->string('bris_dist_pedigree_rating', 8);
            $table->integer('claimed_from_trainer_switches_1_0');
            $table->integer('claimed_from_trainer_switches_1_1');
            $table->integer('claimed_from_trainer_switches_1_2');
            $table->integer('claimed_from_trainer_switches_1_3');
            $table->integer('claimed_from_trainer_switches_1_4');
            $table->integer('claimed_from_trainer_switches_1_5');
            $table->integer('claimed_from_trainer_switches_1_6');
            $table->integer('claimed_from_trainer_switches_1_7');
            $table->integer('claimed_from_trainer_switches_1_8');
            $table->integer('claimed_from_trainer_switches_1_9');
            $table->integer('claimed_from_trainer_switches_2_0');
            $table->integer('claimed_from_trainer_switches_2_1');
            $table->integer('claimed_from_trainer_switches_2_2');
            $table->integer('claimed_from_trainer_switches_2_3');
            $table->integer('claimed_from_trainer_switches_2_4');
            $table->integer('claimed_from_trainer_switches_2_5');
            $table->integer('claimed_from_trainer_switches_2_6');
            $table->integer('claimed_from_trainer_switches_2_7');
            $table->integer('claimed_from_trainer_switches_2_8');
            $table->integer('claimed_from_trainer_switches_2_9');
            $table->integer('claimed_from_trainer_switches_3_0');
            $table->integer('claimed_from_trainer_switches_3_1');
            $table->integer('claimed_from_trainer_switches_3_2');
            $table->integer('claimed_from_trainer_switches_3_3');
            $table->integer('claimed_from_trainer_switches_3_4');
            $table->integer('claimed_from_trainer_switches_3_5');
            $table->integer('claimed_from_trainer_switches_3_6');
            $table->integer('claimed_from_trainer_switches_3_7');
            $table->integer('claimed_from_trainer_switches_3_8');
            $table->integer('claimed_from_trainer_switches_3_9');
            $table->integer('claimed_from_trainer_switches_4_0');
            $table->integer('claimed_from_trainer_switches_4_1');
            $table->integer('claimed_from_trainer_switches_4_2');
            $table->integer('claimed_from_trainer_switches_4_3');
            $table->integer('claimed_from_trainer_switches_4_4');
            $table->integer('claimed_from_trainer_switches_4_5');
            $table->integer('claimed_from_trainer_switches_4_6');
            $table->integer('claimed_from_trainer_switches_4_7');
            $table->integer('claimed_from_trainer_switches_4_8');
            $table->integer('claimed_from_trainer_switches_4_9');
            $table->integer('claimed_from_trainer_switches_5_0');
            $table->integer('claimed_from_trainer_switches_5_1');
            $table->integer('claimed_from_trainer_switches_5_2');
            $table->integer('claimed_from_trainer_switches_5_3');
            $table->integer('claimed_from_trainer_switches_5_4');
            $table->integer('claimed_from_trainer_switches_5_5');
            $table->integer('claimed_from_trainer_switches_5_6');
            $table->integer('claimed_from_trainer_switches_5_7');
            $table->integer('claimed_from_trainer_switches_5_8');
            $table->integer('claimed_from_trainer_switches_5_9');
            $table->integer('claimed_from_trainer_switches_6_0');
            $table->integer('claimed_from_trainer_switches_6_1');
            $table->integer('claimed_from_trainer_switches_6_2');
            $table->integer('claimed_from_trainer_switches_6_3');
            $table->integer('claimed_from_trainer_switches_6_4');
            $table->integer('claimed_from_trainer_switches_6_5');
            $table->integer('claimed_from_trainer_switches_6_6');
            $table->integer('claimed_from_trainer_switches_6_7');
            $table->integer('claimed_from_trainer_switches_6_8');
            $table->integer('claimed_from_trainer_switches_6_9');
            $table->integer('best_bris_speed_life');
            $table->integer('best_bris_speed_most_recent_yr_horse_ran');
            $table->integer('best_bris_speed_2nd_most_recent_yr_horse_ran');
            $table->integer('best_bris_speed_today_track');
            $table->integer('starts_fast_dirt');
            $table->integer('wins_fast_dirt');
            $table->integer('places_fast_dirt');
            $table->integer('shows_fast_dirt');
            $table->integer('earnings_fast_dirt');
            $table->string('key_trnr_stat_category_1', 32);
            $table->integer('of_starts_1');
            $table->float('win_percent_1', 8, 2);
            $table->float('in_the_money_percent_1', 8, 2);
            $table->float('return_on_investment_1', 8, 2);
            $table->string('key_trnr_stat_category_2', 32);
            $table->integer('of_starts_2');
            $table->float('win_percent_2', 8, 2);
            $table->float('in_the_money_percent_2', 8, 2);
            $table->float('return_on_investment_2', 8, 2);
            $table->string('key_trnr_stat_category_3', 32);
            $table->integer('of_starts_3');
            $table->float('win_percent_3', 8, 2);
            $table->float('in_the_money_percent_3', 8, 2);
            $table->float('return_on_investment_3', 8, 2);
            $table->string('key_trnr_stat_category_4', 32);
            $table->integer('of_starts_4');
            $table->float('win_percent_4', 8, 2);
            $table->float('in_the_money_percent_4', 8, 2);
            $table->float('return_on_investment_4', 8, 2);
            $table->string('key_trnr_stat_category_5', 32);
            $table->integer('of_starts_5');
            $table->float('win_percent_5', 8, 2);
            $table->float('in_the_money_percent_5', 8, 2);
            $table->float('return_on_investment_5', 8, 2);
            $table->string('key_trnr_stat_category_6', 32);
            $table->integer('of_starts_6');
            $table->float('win_percent_6', 8, 2);
            $table->float('in_the_money_percent_6', 8, 2);
            $table->float('return_on_investment_6', 8, 2);
            $table->string('jky_dis_jky_on_turf_label', 26);
            $table->integer('jky_dis_jky_on_turf_starts');
            $table->integer('jky_dis_jky_on_turf_wins');
            $table->integer('jky_dis_jky_on_turf_places');
            $table->integer('jky_dis_jky_on_turf_shows');
            $table->integer('jky_dis_jky_on_turf_roi');
            $table->integer('jky_dis_jky_on_turf_earnings');
            $table->string('post_times_by_region', 100);
            $table->string('reserved_1375', 2);
            $table->string('reserved_1376', 2);
            $table->string('reserved_1377', 2);
            $table->string('reserved_1378', 2);
            $table->string('reserved_1379', 2);
            $table->string('reserved_1380', 2);
            $table->string('reserved_1381', 2);
            $table->string('reserved_1382', 2);
            $table->string('extended_start_comment_0', 180);
            $table->string('extended_start_comment_1', 180);
            $table->string('extended_start_comment_2', 180);
            $table->string('extended_start_comment_3', 180);
            $table->string('extended_start_comment_4', 180);
            $table->string('extended_start_comment_5', 180);
            $table->string('extended_start_comment_6', 180);
            $table->string('extended_start_comment_7', 180);
            $table->string('extended_start_comment_8', 180);
            $table->string('extended_start_comment_9', 180);
            $table->string('sealed_track_indicator_0', 2);
            $table->string('sealed_track_indicator_1', 2);
            $table->string('sealed_track_indicator_2', 2);
            $table->string('sealed_track_indicator_3', 2);
            $table->string('sealed_track_indicator_4', 2);
            $table->string('sealed_track_indicator_5', 2);
            $table->string('sealed_track_indicator_6', 2);
            $table->string('sealed_track_indicator_7', 2);
            $table->string('sealed_track_indicator_8', 2);
            $table->string('sealed_track_indicator_9', 2);
            $table->string('prev_all_weather_surface_flag_0', 2);
            $table->string('prev_all_weather_surface_flag_1', 2);
            $table->string('prev_all_weather_surface_flag_2', 2);
            $table->string('prev_all_weather_surface_flag_3', 2);
            $table->string('prev_all_weather_surface_flag_4', 2);
            $table->string('prev_all_weather_surface_flag_5', 2);
            $table->string('prev_all_weather_surface_flag_6', 2);
            $table->string('prev_all_weather_surface_flag_7', 2);
            $table->string('prev_all_weather_surface_flag_8', 2);
            $table->string('prev_all_weather_surface_flag_9', 2);
            $table->integer('tj_combo_starts_meet');
            $table->integer('tj_combo_winss_meet');
            $table->integer('tj_combo_places_meet');
            $table->integer('tj_combo_shows_meet');
            $table->integer('tj_combo_roi_meet');
            $table->string('post_time_pacific_military_time', 8);
            $table->string('equibase_abbrev_race_conditions_0', 35);
            $table->string('equibase_abbrev_race_conditions_1', 35);
            $table->string('equibase_abbrev_race_conditions_2', 35);
            $table->string('equibase_abbrev_race_conditions_3', 35);
            $table->string('equibase_abbrev_race_conditions_4', 35);
            $table->string('equibase_abbrev_race_conditions_5', 35);
            $table->string('equibase_abbrev_race_conditions_6', 35);
            $table->string('equibase_abbrev_race_conditions_7', 35);
            $table->string('equibase_abbrev_race_conditions_8', 35);
            $table->string('equibase_abbrev_race_conditions_9', 35);
            $table->string('today_eqb_abbrev_race_conditions', 35);

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('horses');
    }
}
